### PR TITLE
Dissect-netwayste: Colorize using host+port for uniqueness by default

### PR DESCRIPTION
**Pull request by AaronM04**
Added `--color-option` for either selecting old behavior or disabling color entirely.

### CODE REVIEW

**Review by Manghi — COMMENTED** [review]
What are your thoughts on representing this as multi-valued instead of a boolean for disabling color output too?

Swapping this

```Rust
    #[arg(
        long,
        default_value_t = false,
        help = "Color the output by matching"
    )]
    ignore_port_for_colorizing: bool,
```

with something _like_ 

```Rust
    #[arg(
        long,
        default_value_t = ColorOption::All,
        help = "Narrow the output coloring criteria, one of: All, IPsOnly, None"
    )]
    color_option: ColorOption,

     // . . . 

 enum ColorOption {
    All,
    IPsOnly,
    None,
 }
```

**Comment by AaronM04** [comment]
Works for me!

**Comment by AaronM04** [comment]
@Manghi done! Please merge if it looks good to you. :grinning:

**Comment by Manghi** [comment]
One minor nit is renaming IP/Host to IP/Port. I'll get this in and merge.

**Pull request merged**
